// apps/ns-svelte-mason/src/components/ListItem.svelte
{#if type !== 'c'}
  <view class="li-row">
    <view class={`${type === 'b' ? 'thumb' : 'avatar'} bg-${item.color}`} />
    <view class="li-text">
      <text class="li-title" textContent={item.title} />
      <text class="li-sub" textContent={item.subtitle} />
      {#if type === 'b'}
        <view class="badges">
          {#each item.badges as b}
            <text class={`badge bgl-${item.color}`} textContent={b} />
          {/each}
        </view>
      {/if}
    </view>
    <text class="li-meta" textContent={item.meta} />
  </view>
{:else}
  <view class="li-card">
    <view class="li-card-head">
      <view class={`avatar bg-${item.color}`} />
      <view class="li-text">
        <text class="li-title" textContent={item.title} />
        <text class="li-sub" textContent={item.subtitle} />
      </view>
      <text class="li-meta" textContent={item.meta} />
    </view>
    <text class="li-body" textContent={item.body} />
    <view class="badges">
      {#each item.badges as b}
        <text class={`badge bgl-${item.color}`} textContent={b} />
      {/each}
    </view>
  </view>
{/if}

<script lang="ts">
  import type { ListItem } from '../shared/generate';
  export let type: ListItem['type'];
  export let item: ListItem;
</script>

// apps/ns-vue-mason/src/components/ListItem.vue
<template>
  <View class="li-cell">
    <View v-if="type !== 'c'" class="li-row">
      <View :class="`${type === 'b' ? 'thumb' : 'avatar'} bg-${state.item.color}`" />
      <View class="li-text">
        <Text class="li-title" :textContent="state.item.title" />
        <Text class="li-sub" :textContent="state.item.subtitle" />
        <View v-if="type === 'b'" class="badges">
          <Text v-for="(b, i) in state.item.badges" :key="i" :class="`badge bgl-${state.item.color}`" :textContent="b" />
        </View>
      </View>
      <Text class="li-meta" :textContent="state.item.meta" />
    </View>
    <View v-else class="li-card">
      <View class="li-card-head">
        <View :class="`avatar bg-${state.item.color}`" />
        <View class="li-text">
          <Text class="li-title" :textContent="state.item.title" />
          <Text class="li-sub" :textContent="state.item.subtitle" />
        </View>
        <Text class="li-meta" :textContent="state.item.meta" />
      </View>
      <Text class="li-body" :textContent="state.item.body" />
      <View class="badges">
        <Text v-for="(b, i) in state.item.badges" :key="i" :class="`badge bgl-${state.item.color}`" :textContent="b" />
      </View>
    </View>
  </View>
</template>

<script setup lang="ts">
import type { ListItem } from '../shared/generate';
defineProps<{ type: ListItem['type']; state: { item: ListItem } }>();
</script>
