// apps/ns-svelte-mason/src/components/TextFlow.svelte
<!-- No line clamp in Mason: clamp paragraphs render in full, as in ns-core-mason. -->
<view class="host">
  <view class="text-flow">
    {#each data.paragraphs as p (p.id)}
      {#if p.spacing}
        <text class={`para fs-${p.size}${p.bold ? ' bold' : ''}`} letterSpacing={spacing} textContent={p.text} />
      {:else}
        <text class={`para fs-${p.size}${p.bold ? ' bold' : ''}`} textContent={p.text} />
      {/if}
    {/each}
  </view>
  <Sentinel />
</view>

<script lang="ts">
  import { Screen } from '@nativescript/core';
  import type { TextFlowData } from '../shared/generate';
  import Sentinel from './Sentinel.svelte';
  export let data: TextFlowData;
  /** Mason reads letterSpacing in device pixels. */
  const spacing = 0.5 * Screen.mainScreen.scale;
</script>

// apps/ns-vue-mason/src/components/TextFlow.vue
<!-- No line clamp in Mason: clamp paragraphs render in full, as in ns-core-mason. -->
<template>
  <View>
    <View class="text-flow">
      <template v-for="p in data.paragraphs" :key="p.id">
        <Text v-if="p.spacing" :class="`para fs-${p.size}${p.bold ? ' bold' : ''}`" :letterSpacing="spacing" :textContent="p.text" />
        <Text v-else :class="`para fs-${p.size}${p.bold ? ' bold' : ''}`" :textContent="p.text" />
      </template>
    </View>
    <Sentinel />
  </View>
</template>

<script setup lang="ts">
import { Screen } from '@nativescript/core';
import type { TextFlowData } from '../shared/generate';
import Sentinel from './Sentinel.vue';
defineProps<{ data: TextFlowData }>();
/** Mason reads letterSpacing in device pixels. */
const spacing = 0.5 * Screen.mainScreen.scale;
</script>
