// apps/ns-vue-mason/src/components/ChainLevel.vue
<template>
  <View v-if="level < data.depth" :class="`chain bgl-${level % 8} bc-${level % 8}`">
    <ChainLevel :data="data" :level="level + 1" />
  </View>
  <Text v-else class="chain-label" :textContent="data.label" />
</template>

<script setup lang="ts">
import type { ChainData } from '../shared/generate';
defineProps<{ data: ChainData; level: number }>();
</script>

// apps/ns-svelte-mason/src/components/ChainLevel.svelte
{#if level < data.depth}
  <view class={`chain bgl-${level % 8} bc-${level % 8}`}>
    <svelte:self {data} level={level + 1} />
  </view>
{:else}
  <text class="chain-label" textContent={data.label} />
{/if}

<script lang="ts">
  import type { ChainData } from '../shared/generate';
  export let data: ChainData;
  export let level: number;
</script>
