// apps/ns-vue-mason/src/components/Tiles.vue
<template>
  <View>
    <View class="tiles">
      <View v-for="t in tiles" :key="t.id" :class="`tile bgl-${t.color}`">
        <Text class="tile-title" :textContent="t.title" />
        <Text class="tile-sub" :textContent="t.subtitle" />
      </View>
    </View>
    <Sentinel />
  </View>
</template>

<script setup lang="ts">
import { computed, onUnmounted, ref } from 'nativescript-vue';
import type { TilesData } from '../shared/generate';
import { controller } from '../store';
import Sentinel from './Sentinel.vue';

const props = defineProps<{ data: TilesData }>();
const inserted = ref(false);
const tiles = computed(() => (inserted.value ? [...props.data.insert, ...props.data.tiles] : props.data.tiles));
controller.setMutator((name) => (inserted.value = name === 'insert'));
onUnmounted(() => controller.setMutator(null));
</script>

// apps/ns-svelte-mason/src/components/Tiles.svelte
<view class="host">
  <view class="tiles">
    {#each tiles as t (t.id)}
      <view class={`tile bgl-${t.color}`}>
        <text class="tile-title" textContent={t.title} />
        <text class="tile-sub" textContent={t.subtitle} />
      </view>
    {/each}
  </view>
  <Sentinel />
</view>

<script lang="ts">
  import { onDestroy } from 'svelte';
  import type { TilesData } from '../shared/generate';
  import { controller } from '../store';
  import Sentinel from './Sentinel.svelte';

  export let data: TilesData;
  let inserted = false;
  $: tiles = inserted ? [...data.insert, ...data.tiles] : data.tiles;
  controller.setMutator((name) => (inserted = name === 'insert'));
  onDestroy(() => controller.setMutator(null));
</script>
