// apps/ns-svelte-mason/src/App.svelte
<!-- Same frame as apps/ns-core-mason/app/chrome.ts: a core GridLayout window
     root that only applies the Android system-bar insets, holding a Mason root
     with the status text and a Mason scroll host, or Mason's ul in its place. -->
<gridLayout class="root" androidOverflowEdge="none">
  <view class="frame">
    <text class="status" textContent={$status} />
    {#if $current && $current.fixture === 'list-scroll'}
      <MasonList data={$current.data} />
    {:else}
      <scroll class="body">
        {#if $current}
          <svelte:component this={components[$current.fixture]} data={$current.data} />
        {:else if !$started}
          <Home />
        {/if}
      </scroll>
    {/if}
  </view>
</gridLayout>

<script lang="ts">
  import { current, status, started } from './store';
  import Home from './components/Home.svelte';
  import MasonList from './components/MasonList.svelte';
  import Chain from './components/Chain.svelte';
  import Tree from './components/Tree.svelte';
  import Tiles from './components/Tiles.svelte';
  import Dashboard from './components/Dashboard.svelte';
  import TextFlow from './components/TextFlow.svelte';
  import Cards from './components/Cards.svelte';

  const components: Record<string, any> = {
    'nested-chain': Chain,
    'tree-fanout': Tree,
    'flex-wrap-tiles': Tiles,
    'grid-dashboard': Dashboard,
    'text-flow': TextFlow,
    'styled-cards': Cards,
    'scroll-plain': Cards,
  };
</script>

// apps/ns-react-mason/src/App.tsx
import { controller, current, started, status, useStore } from './store';
import { Home } from './components/Home';
import { MasonList } from './components/MasonList';
import { Cards, Chain, Dashboard, TextFlow, Tiles, Tree } from './components/scenarios';
import type { ListData } from './shared/generate';

const COMPONENTS: Record<string, (p: { data: any }) => any> = {
  'nested-chain': Chain,
  'tree-fanout': Tree,
  'flex-wrap-tiles': Tiles,
  'grid-dashboard': Dashboard,
  'text-flow': TextFlow,
  'styled-cards': Cards,
  'scroll-plain': Cards,
};

// Same frame as apps/ns-core-mason/app/chrome.ts: a core GridLayout that only
// applies the Android system-bar insets, holding a Mason root with the status
// text and a Mason scroll host, or Mason's ul in its place.
export function App() {
  const f = useStore(current);
  const text = useStore(status);
  const isStarted = useStore(started);
  const Scenario = f && COMPONENTS[f.fixture];
  return (
    <gridlayout className="root" androidOverflowEdge="none">
      <view className="frame">
        <text className="status" textContent={text} />
        {f && f.fixture === 'list-scroll' ? (
          <MasonList data={f.data as ListData} />
        ) : (
          <scroll className="body">{Scenario ? <Scenario data={f!.data} /> : !isStarted ? <Home /> : null}</scroll>
        )}
      </view>
    </gridlayout>
  );
}

export { controller };
