// apps/ns-angular-mason/src/main.ts
import { bootstrapApplication, runNativeScriptAngularApp } from '@nativescript/angular';
import { provideZonelessChangeDetection } from '@angular/core';
import { installMasonKit } from '@triniwiz/nativescript-masonkit/angular';
import { onLaunchUrl } from './ns-common/launch';
import { AppComponent } from './app/app.component';
import { launchQueue } from './ns-common/controller';

installMasonKit({ web: false });

onLaunchUrl((url) => launchQueue.push(url));

runNativeScriptAngularApp({
  appModuleBootstrap: () =>
    bootstrapApplication(AppComponent, {
      providers: [provideZonelessChangeDetection()],
    }),
});

// apps/ns-react-mason/src/main.tsx
import { Application } from '@nativescript/core';
import { startReactApp } from '@nativescript-community/react';
import { registerMasonElements } from './ns-dominative/mason-elements';
import { onLaunchUrl } from './ns-common/launch';
import { launchQueue } from './ns-common/controller';
import { App } from './App';

registerMasonElements();

onLaunchUrl((url) => launchQueue.push(url));

startReactApp({ Application, root: <App /> });
