// apps/ns-solid-mason/src/components/MasonList.tsx
import { render } from '@nativescript-community/solid-js';
import { document } from 'dominative';
import { For, createSignal, onMount } from 'solid-js';
import type { ListData, ListItem as Item } from '../shared/generate';
import { controller } from '../store';

// Content of one Ul cell; `type` is fixed per template, `item` is reactive.
function ListItem(props: { type: Item['type']; item: () => Item }) {
  const it = props.item;
  const badges = () => (
    <view class="badges">
      <For each={it().badges}>{(b) => <text class={`badge bgl-${it().color}`} textContent={b} />}</For>
    </view>
  );
  const text = (withBadges: boolean) => (
    <view class="li-text">
      <text class="li-title" textContent={it().title} />
      <text class="li-sub" textContent={it().subtitle} />
      {withBadges ? badges() : null}
    </view>
  );
  if (props.type !== 'c') {
    return (
      <view class="li-row">
        <view class={`${props.type === 'b' ? 'thumb' : 'avatar'} bg-${it().color}`} />
        {text(props.type === 'b')}
        <text class="li-meta" textContent={it().meta} />
      </view>
    );
  }
  return (
    <view class="li-card">
      <view class="li-card-head">
        <view class={`avatar bg-${it().color}`} />
        {text(false)}
        <text class="li-meta" textContent={it().meta} />
      </view>
      <text class="li-body" textContent={it().body} />
      {badges()}
    </view>
  );
}

/**
 * Mason's virtualized ul (masonkit ships no Solid list component). Each keyed
 * template's createView renders a ListItem into a detached .li-cell view (the
 * bare full-width Mason root every Ul cell gets, as in ns-core-mason);
 * itemLoading rebinds the new or recycled cell through its signal.
 */
export function MasonList(props: { data: ListData }) {
  let list: any;
  onMount(() => {
    const items = props.data.items;
    list.itemTemplates = (['a', 'b', 'c'] as const).map((type) => ({
      key: type,
      createView: () => {
        const cell: any = document.createElement('view');
        cell.setAttribute('class', 'li-cell');
        const [item, setItem] = createSignal<Item>(items.find((i) => i.type === type)!);
        render(() => <ListItem type={type} item={item} />, cell);
        cell.__setItem = setItem;
        return cell;
      },
    }));
    list.itemTemplateSelector = (item: Item) => item.type;
    list.on('itemLoading', (args: any) => args.view.__setItem(items[args.index]));
    list.items = items;
  });
  return <ul ref={list} class="list body" on:layoutChanged={() => controller.sentinelLayout()} />;
}

// apps/ns-react-mason/src/components/MasonList.tsx
import { render } from '@nativescript-community/react';
import { document } from 'dominative';
import { useLayoutEffect, useRef } from 'react';
import type { ListData, ListItem as Item } from '../shared/generate';
import { controller, createStore, useStore } from '../store';

// Content of one Ul cell; `type` is fixed per template.
function ListItem({ type, item }: { type: Item['type']; item: Item }) {
  const badges = (
    <view className="badges">
      {item.badges.map((b, i) => (
        <text key={i} className={`badge bgl-${item.color}`} textContent={b} />
      ))}
    </view>
  );
  const text = (withBadges: boolean) => (
    <view className="li-text">
      <text className="li-title" textContent={item.title} />
      <text className="li-sub" textContent={item.subtitle} />
      {withBadges ? badges : null}
    </view>
  );
  if (type !== 'c') {
    return (
      <view className="li-row">
        <view className={`${type === 'b' ? 'thumb' : 'avatar'} bg-${item.color}`} />
        {text(type === 'b')}
        <text className="li-meta" textContent={item.meta} />
      </view>
    );
  }
  return (
    <view className="li-card">
      <view className="li-card-head">
        <view className={`avatar bg-${item.color}`} />
        {text(false)}
        <text className="li-meta" textContent={item.meta} />
      </view>
      <text className="li-body" textContent={item.body} />
      {badges}
    </view>
  );
}

function Cell({ type, store }: { type: Item['type']; store: ReturnType<typeof createStore<Item>> }) {
  return <ListItem type={type} item={useStore(store)} />;
}

/**
 * Mason's virtualized ul (masonkit ships no React list component). Each keyed
 * template's createView renders a Cell root into a detached .li-cell view (the
 * bare full-width Mason root every Ul cell gets, as in ns-core-mason);
 * itemLoading rebinds the new or recycled cell through its store.
 */
export function MasonList({ data }: { data: ListData }) {
  const ref = useRef<any>(null);
  useLayoutEffect(() => {
    const list = ref.current;
    list.itemTemplates = (['a', 'b', 'c'] as const).map((type) => ({
      key: type,
      createView: () => {
        const cell: any = document.createElement('view');
        cell.className = 'li-cell';
        const store = createStore<Item>(data.items.find((i) => i.type === type)!);
        render(<Cell type={type} store={store} />, cell);
        cell.__store = store;
        return cell;
      },
    }));
    list.itemTemplateSelector = (item: Item) => item.type;
    list.on('itemLoading', (args: any) => args.view.__store.set(data.items[args.index]));
    list.items = data.items;
  }, [data]);
  return <ul ref={ref} className="list body" onLayoutChanged={() => controller.sentinelLayout()} />;
}
